[package]
name = "ketos"
version = "0.10.0"
authors = ["Murarth <murarth@gmail.com>"]

description = "Lisp dialect scripting and extension language"

documentation = "https://docs.rs/ketos/"
homepage = "https://github.com/murarth/ketos"
repository = "https://github.com/murarth/ketos"

keywords = [ "scripting", "extension", "functional", "language", "lisp" ]
license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
name = "ketos"

[dependencies]
byteorder = "0.5.1"
gumdrop = "0.5"
num = "0.2"
rand = "0.5"
serde = { version = "1.0", optional = true }
# Used only in `tests/value_derive.rs`
serde_derive = { version = "1.0", optional = true }

[target.'cfg(any(unix,windows))'.dependencies]
dirs = "1.0"
linefeed = "0.5.3"

[dev-dependencies]
assert_matches = "1.0"
ketos_derive = { version = "0.10", path = "../ketos_derive" }
